### ISSUE TITLE
更新nb2后关于apscheduler的插件都报错

### ISSUE THREAD

**Issue by Parirose** [nonebot/plugin-apscheduler#29]
```python
07-08 14:48:07 [ERROR] nonebot | Failed to import "nonebot_plugin_apscheduler"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\load.py", line 125,
 in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\load.py", line 62,
in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
75, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
76, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
41, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_m
odule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 2
40, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot_plugin_lolmatch\__init__.p
y", line 38, in <module>
    require("nonebot_plugin_apscheduler")
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\load.py", line 166,
 in require
    plugin = manager.load_plugin(name)
> File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
41, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_m
odule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 2
40, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot_plugin_apscheduler\__init_
_.py", line 10, in <module>
    __plugin_meta__ = PluginMetadata(
TypeError: PluginMetadata.__init__() got an unexpected keyword argument 'type'
```

apscheduler的报错 其他似乎是一样的问题 是不适配nonebot2最新版本吗？

**Comment by yanyongyu** [comment]
这报错是你nb2版本没有升级到最新。。。

**Comment by Parirose** [comment]
> 这报错是你nb2版本没有升级到最新。。。

感谢 解决了
