### ISSUE TITLE
添加配置后无法加载插件

### ISSUE THREAD

**Issue by lingyunQAQ** [nonebot/plugin-apscheduler#30]
```python
from pydantic import Field, BaseSettings
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
import datetime
from apscheduler.executors.pool import ThreadPoolExecutor, ProcessPoolExecutor

from apscheduler.schedulers.background import BackgroundScheduler

jobstores = {
    'default': SQLAlchemyJobStore(url='sqlite:///sql.sqlite')
}
executors = {
    'default': ThreadPoolExecutor(20),
    'processpool': ProcessPoolExecutor(20)
}
job_defaults = {
    'coalesce': True,
    'max_instances': 10
}


class Config(BaseSettings):
    apscheduler_autostart: bool = True
    apscheduler_log_level: int = 30
    apscheduler_config: dict = Field(
        default_factory=lambda: {"apscheduler.timezone": "Asia/Shanghai",
                                 "apscheduler.next_run_time": f"{datetime.datetime.now().astimezone()}",
                                 "apscheduler.jobstores": jobstores,
                                 "apscheduler.executors": executors,
                                 "apscheduler.job_defaults": job_defaults}
    )

    class Config:
        extra = "ignore"
```

如上，我添加了next_run_time，jobstores，executors,job_defaults，后就不能加载插件了
报错信息如下：
```python
07-09 21:59:44 [ERROR] nonebot | Failed to import "nonebot_plugin_apscheduler"
Traceback (most recent call last):
  File "D:\桌面\usdt机器人\USDT\bot.py", line 15, in <module>
    nonebot.load_plugins("plugins/usdt")  # 本地插件
  File "D:\桌面\usdt机器人\USDT\.venv\lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "D:\桌面\usdt机器人\USDT\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\桌面\usdt机器人\USDT\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "D:\桌面\usdt机器人\USDT\.venv\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\桌面\usdt机器人\USDT\plugins\usdt\__init__.py", line 33, in <module>
    require("nonebot_plugin_apscheduler")
  File "D:\桌面\usdt机器人\USDT\.venv\lib\site-packages\nonebot\plugin\load.py", line 174, in require
    plugin = load_plugin(name)
  File "D:\桌面\usdt机器人\USDT\.venv\lib\site-packages\nonebot\plugin\load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
> File "D:\桌面\usdt机器人\USDT\.venv\lib\site-packages\nonebot\plugin\manager.py", line 154, in load_plugin
    raise RuntimeError(
RuntimeError: Module nonebot_plugin_apscheduler is not loaded as a plugin! Make sure not to import it before loading.
```

**Comment by yanyongyu** [comment]
请检查你是否在加载插件前import了任何插件

**Comment by lingyunQAQ** [comment]
> 请检查你是否在加载插件前import了任何插件

有一个echo

**Comment by lingyunQAQ** [comment]
> 请检查你是否在加载插件前import了任何插件

我删除了require("nonebot_plugin_apscheduler")就不会报错了，请问这会影响使用吗

**Comment by yanyongyu** [comment]
会影响使用，请注意不要再nonebot.load_plugins上方进行任何的import插件操作，你再检查一下吧

**Comment by lingyunQAQ** [comment]
> 会影响使用，请注意不要再nonebot.load_plugins上方进行任何的import插件操作，你再检查一下吧

emm，问一下，如果我的sql文件放在工程目录下(同bot.py)那么我的配置这样子写可以吗

**Comment by yanyongyu** [comment]
不要在加载插件前import插件模块即可
